# Configuration for probot-min-reviews - https://github.com/raulriera/probot-minimum-reviews
_extends: .github

# Number of reviews required to mark the pull request as valid
reviewsUntilReady: 2

# Number of changes in the pull request to start enforcing the reviewsUntilReady rule
changesThreshold: 100

# URL the users are taken to when clicking the commit status
statusUrl: 'https://github.com/apps/minimum-reviews'

# Message to display when the commit status passes
readyMessage: 'No pending reviews'

# Message to display when the commit status fails
notReadyMessage: 'Pending review approvals'

# Status to set the commit to when waiting for reviews
# 'failure, error, and pending' are the suggested options
notReadyState: 'pending'
